# Site settings
author: Rae Emard 
title: (Zen)trepreneur 
header-img: img/home-bg.png
email: raeliseemard@gmail.com
copyright_name: Rae Emard 
description: > # this means to ignore newlines until "baseurl:"
  tranistioning to a technical founder without loosing my mind 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  raelisee

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
